#!/usr/bin/env python3
"""
Company Profile Builder — enriches all jobs with:
- Company logo (scraped from website)
- 5-6 sentence company bio (generated by llama3.1:8b)
- Standardized fields (industry, size, founded)
Runs once to enrich all 11K jobs, then updates periodically.
"""
import json, urllib.request, subprocess, re, os, time, hashlib
from collections import defaultdict
from urllib.parse import urljoin, urlparse

MODEL = "llama3.1:8b"
DATA_FILE = "/Volumes/Data/Deepseek_Awesome/data/jobs.json"
LOGOS_DIR = "/Volumes/Data/Deepseek_Awesome/assets/company-logos"
CACHE_FILE = "/Volumes/Data/Deepseek_Awesome/data/company_profiles.json"

os.makedirs(LOGOS_DIR, exist_ok=True)

def llm(prompt, max_tokens=400):
    try:
        r = subprocess.run(["ollama", "run", MODEL], input=prompt.encode(),
                          capture_output=True, timeout=45)
        text = r.stdout.decode().strip()
        text = re.sub(r'<think>.*?</think>', '', text, flags=re.DOTALL)
        text = re.sub(r'```.*?```', '', text, flags=re.DOTALL)
        return text.strip()
    except: return ""

def fetch_page(url, timeout=8):
    try:
        req = urllib.request.Request(url)
        req.add_header("User-Agent", "Mozilla/5.0")
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return r.read().decode("utf-8", errors="replace")
    except: return None

def find_logo(html, base_url):
    """Extract company logo from website HTML."""
    # Common logo patterns
    patterns = [
        r'<img[^>]+src=["\']([^"\']*logo[^"\']*\.(?:png|svg|jpg|jpeg|webp))["\']',
        r'<img[^>]+src=["\']([^"\']*brand[^"\']*\.(?:png|svg|jpg|jpeg|webp))["\']',
        r'<link[^>]+rel=["\'](?:icon|shortcut icon)["\'][^>]+href=["\']([^"\']+)["\']',
        r'<meta[^>]+property=["\']og:image["\'][^>]+content=["\']([^"\']+)["\']',
    ]
    for pattern in patterns:
        match = re.search(pattern, html, re.IGNORECASE)
        if match:
            logo_url = match.group(1)
            if logo_url.startswith('//'): logo_url = 'https:' + logo_url
            elif logo_url.startswith('/'): logo_url = urljoin(base_url, logo_url)
            elif not logo_url.startswith('http'): logo_url = urljoin(base_url, logo_url)
            return logo_url
    return None

def download_logo(url, company_name):
    """Download logo to local directory."""
    slug = re.sub(r'[^a-z0-9]', '-', company_name.lower())[:40].strip('-')
    path = f"{LOGOS_DIR}/{slug}.png"
    if os.path.exists(path): return f"/assets/company-logos/{slug}.png"
    try:
        req = urllib.request.Request(url)
        req.add_header("User-Agent", "Mozilla/5.0")
        data = urllib.request.urlopen(req, timeout=10).read()
        if len(data) > 500:
            with open(path, 'wb') as f: f.write(data)
            return f"/assets/company-logos/{slug}.png"
    except: pass
    return None

def generate_profile(company_name, job_titles, html_sample=""):
    """Generate 5-6 sentence company profile + facts."""
    jobs_text = ', '.join(job_titles[:10])
    sample_text = re.sub(r'<[^>]+>', ' ', html_sample[:3000]) if html_sample else ""
    
    prompt = f"""Research {company_name}. They are hiring for: {jobs_text}.

{f'Website text: {sample_text[:2000]}' if sample_text else ''}

Return ONLY JSON (no markdown):
{{
  "about": "5-6 sentence company bio. What they do, size, culture, notable facts, why people want to work there.",
  "industry": "primary industry (1-3 words)",
  "size": "small/medium/large/enterprise",
  "founded": "year or decade if known"
}}"""

    try:
        text = llm(prompt)
        m = re.search(r'\{.*\}', text, re.DOTALL)
        if m: return json.loads(m.group())
    except: pass
    
    # Fallback
    return {"about": f"{company_name} is a company hiring for remote positions.", "industry": "Technology", "size": "medium", "founded": ""}

# ── Main ──
print("🏢 Company Profile Builder")
print()

# Load data
with open(DATA_FILE) as f:
    data = json.load(f)

# Load existing profiles
profiles = {}
if os.path.exists(CACHE_FILE):
    with open(CACHE_FILE) as f:
        profiles = json.load(f)

# Group jobs by company
companies = defaultdict(lambda: {"jobs": [], "count": 0})
for j in data["jobs"]:
    co = (j.get("company") or "Unknown").strip()
    if not co or co.lower() in ("various", "unknown", "various (proz)"): continue
    companies[co]["jobs"].append(j)
    companies[co]["count"] += 1

sorted_companies = sorted(companies.items(), key=lambda x: x[1]["count"], reverse=True)
print(f"📊 {len(sorted_companies)} unique companies")

# Process top companies (limit to 200 for speed, rest later)
to_process = sorted_companies[:200]
print(f"🔄 Processing top {len(to_process)} companies...")

enriched = 0
for i, (name, info) in enumerate(to_process):
    if name in profiles:
        # Already have profile, just apply to jobs
        p = profiles[name]
        for j in info["jobs"]:
            j["_company_logo"] = p.get("logo")
            j["_company_about"] = p.get("about")
            j["_company_industry"] = p.get("industry")
            j["_company_size"] = p.get("size")
            j["_company_founded"] = p.get("founded")
        enriched += info["count"]
        continue
    
    if (i+1) % 20 == 0: print(f"  {i+1}/{len(to_process)} companies processed...")
    
    profile = profiles.get(name, {})
    job_titles = [j.get("title","") for j in info["jobs"][:20]]
    
    # Try to find company website
    company_url = f"https://{name.lower().replace(' ','')}.com"
    html = fetch_page(company_url)
    if not html:
        # Try alternative URLs
        for alt in [f"https://www.{name.lower().replace(' ','')}.com",
                    f"https://{name.lower().replace(' ','').replace('-','')}.com"]:
            html = fetch_page(alt)
            if html: break
    
    # Find logo
    logo = None
    if html:
        logo_url = find_logo(html, company_url)
        if logo_url:
            logo = download_logo(logo_url, name)
            if logo: profile["logo"] = logo
    
    # Generate profile
    gen = generate_profile(name, job_titles, html or "")
    profile["about"] = gen.get("about", "")
    profile["industry"] = gen.get("industry", "")
    profile["size"] = gen.get("size", "")
    profile["founded"] = gen.get("founded", "")
    
    profiles[name] = profile
    
    # Apply to all jobs for this company
    for j in info["jobs"]:
        j["_company_logo"] = profile.get("logo")
        j["_company_about"] = profile.get("about")
        j["_company_industry"] = profile.get("industry")
        j["_company_size"] = profile.get("size")
        j["_company_founded"] = profile.get("founded")
    enriched += info["count"]

# Save profiles cache
with open(CACHE_FILE, "w") as f:
    json.dump(profiles, f, indent=2)

# Save enriched data
data["meta"]["enriched_at"] = time.strftime("%Y-%m-%dT%H:%M:%SZ")
with open(DATA_FILE, "w") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"\n✅ Enriched {enriched} jobs across {len(profiles)} companies")
print(f"📁 Profiles saved to {CACHE_FILE}")
print(f"🖼  Logos saved to {LOGOS_DIR}/")
